### ISSUE TITLE
Azure connection overhaul

### ISSUE THREAD

**Issue by pavelzag** [Trolley-MGMT/trolleymgmt#28]
At the moment we work with Azure using a CLI. We need to replace it with a proper Python based connector

**Comment by m3llo96** [comment]
Hello @pavelzag, I'm Roee Ninyo from the "Pull Request" Community. I would appreciate it if @LiorYardeni could reach out to me regarding an issue that I might be able to help with. Thank you.

Please let me know if there's anything else I can assist you with.

**Comment by liorko87** [comment]
I did something like this in the past.
Take a look here and tell me if it's satisfy your needs
https://github.com/cryptobiu/MATRIX/blob/master/Deployment/azure_deploy.py#L362

**Comment by pavelzag** [comment]
@liorko87 I see the code deals with building VMs on Azure. Trolley, at the moment, deals more with Kubernetes (AKS on Azure) and deployments on it

**Comment by pavelzag** [comment]
Done
